"""empty message

Revision ID: 17cd416886cb
Revises: ed80bb5d4542
Create Date: 2023-01-22 00:50:17.726702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cd416886cb'
down_revision = 'ed80bb5d4542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pools', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pools', 'has_equipment_rental',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_tech_service',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_dressing_room',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_eatery',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_toilets',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_wifi',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_cash_machine',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_first_aid_post',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'has_music',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('pools', 'how_suitable_for_disabled',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pools', 'how_suitable_for_disabled',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pools', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_music',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_first_aid_post',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_cash_machine',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_wifi',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_toilets',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_eatery',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_dressing_room',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_tech_service',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'has_equipment_rental',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pools', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
