"""empty message

Revision ID: 52075fcdc411
Revises: 17cd416886cb
Create Date: 2023-01-22 00:50:51.883853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52075fcdc411'
down_revision = '17cd416886cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pools', 'web_site',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pools', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pools', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pools', 'web_site',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
