"""first

Revision ID: df9674cbf3fa
Revises: efa2d77276c8
Create Date: 2023-01-19 12:24:32.612345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9674cbf3fa'
down_revision = 'efa2d77276c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pools',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('web_site', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('administrative_area', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('has_equipment_rental', sa.Boolean(), nullable=False),
    sa.Column('has_tech_service', sa.Boolean(), nullable=False),
    sa.Column('has_dressing_room', sa.Boolean(), nullable=False),
    sa.Column('has_eatery', sa.Boolean(), nullable=False),
    sa.Column('has_toilets', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_cash_machine', sa.Boolean(), nullable=False),
    sa.Column('has_first_aid_post', sa.Boolean(), nullable=False),
    sa.Column('has_music', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('how_suitable_for_disabled', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pools')
    # ### end Alembic commands ###
